
# Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
# Click nbfs://nbhost/SystemFileSystem/Templates/Other/properties.properties to edit this template


google.clientId=404365163109-1q2otq7j50mhnlms71d5jvukckm8ps9g.apps.googleusercontent.com